import type { Locale, SiteContent } from './types'
import { dictionaries } from './dictionaries'
import * as shared from './shared'

export function buildContent(locale: Locale): SiteContent {
  const dict = dictionaries[locale]

  const navLinks = [
    { href: '#about', label: dict.nav.about },
    { href: '#work', label: dict.nav.work },
    { href: '#gallery', label: dict.nav.gallery },
    { href: '#experience', label: dict.nav.experience },
    { href: '#skills', label: dict.nav.skills },
    { href: '#contact', label: dict.nav.contact },
  ]

  return {
    navLinks,
    socialLinks: shared.socialLinks,
    logo: shared.logo,
    cvButtonLabel: shared.cvButtonLabel,
    cvShortButtonLabel: shared.cvShortButtonLabel,
    hero: {
      eyebrow: dict.hero.eyebrow,
      titleWhite: dict.hero.titleWhite,
      titlePink: dict.hero.titlePink,
      subtitle: dict.hero.subtitle,
      ctaPrimary: dict.hero.ctaPrimary,
      sticker1: dict.hero.sticker1,
      sticker2: dict.hero.sticker2,
    },
    skillsStickerText: dict.skillsStickerText,
    liveStickerText: dict.liveStickerText,
    projectsSectionTitle: dict.projectsSectionTitle,
    codeOnGithubText: dict.codeOnGithubText,
    seeGalleryText: dict.seeGalleryText,
    gallery: {
      sectionTitle: dict.gallery.sectionTitle,
      subtitle: dict.gallery.subtitle,
      items: shared.galleryAssets.map((asset, i) => ({ ...asset, caption: dict.gallery.captions[i] })),
    },
    showcaseProjects: [
      {
        id: 'langlib',
        tabLabel: dict.projects.langLib.tabLabel,
        status: dict.projects.langLib.status,
        title: dict.projects.langLib.title,
        description: dict.projects.langLib.description,
        stack: shared.projectStack.langLib,
      },
      {
        id: 'flashcards',
        tabLabel: dict.projects.flashcards.tabLabel,
        status: dict.projects.flashcards.status,
        title: dict.projects.flashcards.title,
        description: dict.projects.flashcards.description,
        stack: shared.projectStack.flashcards,
        githubUrl: 'https://github.com/Sakitsudzukeru/flashcards',
      },
      {
        id: 'cdr-parser',
        tabLabel: dict.projects.cdrParser.tabLabel,
        status: dict.projects.cdrParser.status,
        title: dict.projects.cdrParser.title,
        description: dict.projects.cdrParser.description,
        stack: shared.projectStack.cdrParser,
        githubUrl: 'https://github.com/Sakitsudzukeru/parser',
      },
      {
        id: 'moderation',
        tabLabel: dict.projects.moderation.tabLabel,
        status: dict.projects.moderation.status,
        title: dict.projects.moderation.title,
        description: dict.projects.moderation.description,
        stack: shared.projectStack.moderation,
        githubUrl: 'https://github.com/Sakitsudzukeru/image-moderation-service',
      },
      {
        id: 'sticker',
        tabLabel: dict.projects.sticker.tabLabel,
        status: dict.projects.sticker.status,
        title: dict.projects.sticker.title,
        description: dict.projects.sticker.description,
        stack: shared.projectStack.sticker,
        githubUrl: 'https://github.com/Sakitsudzukeru/my-profile/blob/main/src/components/StickyNote.vue',
        code: {
          kind: 'tabs',
          tabs: [
            { label: 'CSS', html: shared.buildStickerCssTab(dict.projects.sticker.cssComment) },
            { label: 'HTML', html: shared.buildStickerHtmlTab(dict.projects.sticker.htmlComment, dict.skillsStickerText) },
            { label: 'React', html: shared.buildStickerReactTab(dict.projects.sticker.reactComment, dict.skillsStickerText) },
          ],
        },
        result: { kind: 'live', text: dict.liveStickerText },
      },
      {
        id: 'cat-runner',
        tabLabel: dict.projects.catRunner.tabLabel,
        status: dict.projects.catRunner.status,
        title: dict.projects.catRunner.title,
        description: dict.projects.catRunner.description,
        stack: shared.projectStack.catRunner,
        githubUrl: 'https://github.com/Sakitsudzukeru/my-profile/blob/main/src/components/game/CatRunnerGame.vue',
        code: { kind: 'single', filename: shared.catRunnerFilename, html: shared.catRunnerCode },
        result: { kind: 'game' },
      },
      {
        id: 'memory-game',
        tabLabel: dict.projects.memoryGame.tabLabel,
        status: dict.projects.memoryGame.status,
        title: dict.projects.memoryGame.title,
        description: dict.projects.memoryGame.description,
        stack: shared.projectStack.memoryGame,
        githubUrl: 'https://github.com/Sakitsudzukeru/my-profile/blob/main/src/components/game/MemoryGame.vue',
        code: { kind: 'single', filename: shared.memoryGameFilename, html: shared.memoryGameCode },
        result: { kind: 'memory' },
      },
      {
        id: 'whack-a-mole',
        tabLabel: dict.projects.whackAMole.tabLabel,
        status: dict.projects.whackAMole.status,
        title: dict.projects.whackAMole.title,
        description: dict.projects.whackAMole.description,
        stack: shared.projectStack.whackAMole,
        githubUrl: 'https://github.com/Sakitsudzukeru/my-profile/blob/main/src/components/game/WhackAMole.vue',
        code: { kind: 'single', filename: shared.whackAMoleFilename, html: shared.whackAMoleCode },
        result: { kind: 'whack' },
      },
    ],
    skillsSectionTitle: dict.skillsSectionTitle,
    skillGroups: [
      { label: dict.skillGroupLabels.backend, tiles: shared.skillTilesByGroup.backend },
      { label: dict.skillGroupLabels.frontend, tiles: shared.skillTilesByGroup.frontend },
      { label: dict.skillGroupLabels.mobile, tiles: shared.skillTilesByGroup.mobile },
      { label: dict.skillGroupLabels.data, tiles: shared.skillTilesByGroup.data },
      { label: dict.skillGroupLabels.devops, tiles: shared.skillTilesByGroup.devops },
      { label: dict.skillGroupLabels.design, tiles: shared.skillTilesByGroup.design },
    ],
    experienceSectionTitle: dict.experienceSectionTitle,
    timeline: dict.timeline,
    aboutSectionTitle: dict.aboutSectionTitle,
    aboutText: dict.aboutText,
    aboutFacts: dict.aboutFacts,
    personalFacts: dict.personalFacts,
    educationSectionTitle: dict.educationSectionTitle,
    education: dict.education,
    coursesLabel: dict.coursesLabel,
    courses: dict.courses,
    footer: {
      headingBefore: dict.footer.headingBefore,
      headingAfter: dict.footer.headingAfter,
      headingHighlight: dict.footer.headingHighlight,
      email: shared.footerEmail,
      location: dict.footer.location,
      stickyLine1: dict.footer.stickyLine1,
      stickyLine2: dict.footer.stickyLine2,
    },
    footerBottom: dict.footerBottom,
    common: dict.common,
    runner: dict.runner,
    memory: dict.memory,
    whack: dict.whack,
  }
}
